/// Upazilas (sub-districts) of Bangladesh, keyed by district name.
///
/// Source: standard Bangladesh administrative division list. Cross-check
/// against an authoritative source before relying on it for anything beyond
/// this form's dropdown.
const Map<String, List<String>> bdUpazilas = {
  'Bagerhat': [
    'Bagerhat Sadar',
    'Chitalmari',
    'Fakirhat',
    'Kachua',
    'Mollahat',
    'Mongla',
    'Morrelganj',
    'Rampal',
    'Sarankhola',
  ],
  'Bandarban': [
    'Alikadam',
    'Bandarban Sadar',
    'Lama',
    'Naikhongchhari',
    'Rowangchhari',
    'Ruma',
    'Thanchi',
  ],
  'Barguna': [
    'Amtali',
    'Bamna',
    'Barguna Sadar',
    'Betagi',
    'Patharghata',
    'Taltali',
  ],
  'Barishal': [
    'Agailjhara',
    'Babuganj',
    'Bakerganj',
    'Banaripara',
    'Barishal Sadar',
    'Gaurnadi',
    'Hizla',
    'Mehendiganj',
    'Muladi',
    'Wazirpur',
  ],
  'Bhola': [
    'Bhola Sadar',
    'Burhanuddin',
    'Char Fasson',
    'Daulatkhan',
    'Lalmohan',
    'Manpura',
    'Tazumuddin',
  ],
  'Bogura': [
    'Adamdighi',
    'Bogura Sadar',
    'Dhunat',
    'Dhupchanchia',
    'Gabtali',
    'Kahaloo',
    'Nandigram',
    'Sariakandi',
    'Shajahanpur',
    'Sherpur',
    'Shibganj',
    'Sonatola',
  ],
  'Brahmanbaria': [
    'Akhaura',
    'Ashuganj',
    'Bancharampur',
    'Bijoynagar',
    'Brahmanbaria Sadar',
    'Kasba',
    'Nabinagar',
    'Nasirnagar',
    'Sarail',
  ],
  'Chandpur': [
    'Chandpur Sadar',
    'Faridganj',
    'Haimchar',
    'Haziganj',
    'Kachua',
    'Matlab Dakshin',
    'Matlab Uttar',
    'Shahrasti',
  ],
  'Chattogram': [
    'Anwara',
    'Banshkhali',
    'Boalkhali',
    'Chandanaish',
    'Fatikchhari',
    'Hathazari',
    'Lohagara',
    'Mirsharai',
    'Patiya',
    'Rangunia',
    'Raozan',
    'Sandwip',
    'Satkania',
    'Sitakunda',
  ],
  'Chuadanga': [
    'Alamdanga',
    'Chuadanga Sadar',
    'Damurhuda',
    'Jibannagar',
  ],
  "Cox's Bazar": [
    'Chakaria',
    "Cox's Bazar Sadar",
    'Kutubdia',
    'Maheshkhali',
    'Pekua',
    'Ramu',
    'Teknaf',
    'Ukhia',
  ],
  'Cumilla': [
    'Barura',
    'Brahmanpara',
    'Burichang',
    'Chandina',
    'Chauddagram',
    'Cumilla Adarsha Sadar',
    'Cumilla Sadar Dakshin',
    'Daudkandi',
    'Debidwar',
    'Homna',
    'Laksam',
    'Lalmai',
    'Meghna',
    'Monohorgonj',
    'Muradnagar',
    'Nangalkot',
    'Titas',
  ],
  'Dhaka': [
    'Dhamrai',
    'Dohar',
    'Keraniganj',
    'Nawabganj',
    'Savar',
  ],
  'Dinajpur': [
    'Biral',
    'Birampur',
    'Birganj',
    'Bochaganj',
    'Chirirbandar',
    'Dinajpur Sadar',
    'Fulbari',
    'Ghoraghat',
    'Hakimpur',
    'Kaharole',
    'Khansama',
    'Nawabganj',
    'Parbatipur',
  ],
  'Faridpur': [
    'Alfadanga',
    'Bhanga',
    'Boalmari',
    'Charbhadrasan',
    'Faridpur Sadar',
    'Madhukhali',
    'Nagarkanda',
    'Sadarpur',
    'Saltha',
  ],
  'Feni': [
    'Chhagalnaiya',
    'Daganbhuiyan',
    'Feni Sadar',
    'Fulgazi',
    'Parshuram',
    'Sonagazi',
  ],
  'Gaibandha': [
    'Fulchhari',
    'Gaibandha Sadar',
    'Gobindaganj',
    'Palashbari',
    'Sadullapur',
    'Saghata',
    'Sundarganj',
  ],
  'Gazipur': [
    'Kaliakair',
    'Kaliganj',
    'Kapasia',
    'Gazipur Sadar',
    'Sreepur',
  ],
  'Gopalganj': [
    'Gopalganj Sadar',
    'Kashiani',
    'Kotalipara',
    'Muksudpur',
    'Tungipara',
  ],
  'Habiganj': [
    'Ajmiriganj',
    'Bahubal',
    'Baniyachong',
    'Chunarughat',
    'Habiganj Sadar',
    'Lakhai',
    'Madhabpur',
    'Nabiganj',
    'Shayestaganj',
  ],
  'Jamalpur': [
    'Bakshiganj',
    'Dewanganj',
    'Islampur',
    'Jamalpur Sadar',
    'Madarganj',
    'Melandaha',
    'Sarishabari',
  ],
  'Jashore': [
    'Abhaynagar',
    'Bagherpara',
    'Chaugachha',
    'Jashore Sadar',
    'Jhikargachha',
    'Keshabpur',
    'Manirampur',
    'Sharsha',
  ],
  'Jhalokati': [
    'Jhalokati Sadar',
    'Kathalia',
    'Nalchity',
    'Rajapur',
  ],
  'Jhenaidah': [
    'Harinakunda',
    'Jhenaidah Sadar',
    'Kaliganj',
    'Kotchandpur',
    'Maheshpur',
    'Shailkupa',
  ],
  'Joypurhat': [
    'Akkelpur',
    'Joypurhat Sadar',
    'Kalai',
    'Khetlal',
    'Panchbibi',
  ],
  'Khagrachhari': [
    'Dighinala',
    'Khagrachhari Sadar',
    'Lakshmichhari',
    'Mahalchhari',
    'Manikchhari',
    'Matiranga',
    'Panchhari',
    'Ramgarh',
  ],
  'Khulna': [
    'Batiaghata',
    'Dacope',
    'Dumuria',
    'Dighalia',
    'Koyra',
    'Paikgachha',
    'Phultala',
    'Rupsa',
    'Terokhada',
  ],
  'Kishoreganj': [
    'Austagram',
    'Bajitpur',
    'Bhairab',
    'Hossainpur',
    'Itna',
    'Karimganj',
    'Katiadi',
    'Kishoreganj Sadar',
    'Kuliarchar',
    'Mithamain',
    'Nikli',
    'Pakundia',
    'Tarail',
  ],
  'Kurigram': [
    'Bhurungamari',
    'Char Rajibpur',
    'Chilmari',
    'Kurigram Sadar',
    'Nageshwari',
    'Phulbari',
    'Rajarhat',
    'Raomari',
    'Ulipur',
  ],
  'Kushtia': [
    'Bheramara',
    'Daulatpur',
    'Khoksa',
    'Kumarkhali',
    'Kushtia Sadar',
    'Mirpur',
  ],
  'Lakshmipur': [
    'Kamalnagar',
    'Lakshmipur Sadar',
    'Raipur',
    'Ramganj',
    'Ramgati',
  ],
  'Lalmonirhat': [
    'Aditmari',
    'Hatibandha',
    'Kaliganj',
    'Lalmonirhat Sadar',
    'Patgram',
  ],
  'Madaripur': [
    'Kalkini',
    'Madaripur Sadar',
    'Rajoir',
    'Shibchar',
  ],
  'Magura': [
    'Magura Sadar',
    'Mohammadpur',
    'Shalikha',
    'Sreepur',
  ],
  'Manikganj': [
    'Daulatpur',
    'Ghior',
    'Harirampur',
    'Manikganj Sadar',
    'Saturia',
    'Shibalaya',
    'Singair',
  ],
  'Meherpur': [
    'Gangni',
    'Meherpur Sadar',
    'Mujibnagar',
  ],
  'Moulvibazar': [
    'Barlekha',
    'Juri',
    'Kamalganj',
    'Kulaura',
    'Moulvibazar Sadar',
    'Rajnagar',
    'Sreemangal',
  ],
  'Munshiganj': [
    'Gazaria',
    'Lohajang',
    'Munshiganj Sadar',
    'Sirajdikhan',
    'Sreenagar',
    'Tongibari',
  ],
  'Mymensingh': [
    'Bhaluka',
    'Dhobaura',
    'Fulbaria',
    'Gaffargaon',
    'Gauripur',
    'Haluaghat',
    'Ishwarganj',
    'Muktagachha',
    'Mymensingh Sadar',
    'Nandail',
    'Phulpur',
    'Trishal',
  ],
  'Naogaon': [
    'Atrai',
    'Badalgachhi',
    'Dhamoirhat',
    'Manda',
    'Mahadebpur',
    'Naogaon Sadar',
    'Niamatpur',
    'Patnitala',
    'Porsha',
    'Raninagar',
    'Sapahar',
  ],
  'Narail': [
    'Kalia',
    'Lohagara',
    'Narail Sadar',
  ],
  'Narayanganj': [
    'Araihazar',
    'Bandar',
    'Narayanganj Sadar',
    'Rupganj',
    'Sonargaon',
  ],
  'Narsingdi': [
    'Belabo',
    'Monohardi',
    'Narsingdi Sadar',
    'Palash',
    'Raipura',
    'Shibpur',
  ],
  'Natore': [
    'Bagatipara',
    'Baraigram',
    'Gurudaspur',
    'Lalpur',
    'Natore Sadar',
    'Singra',
  ],
  'Netrokona': [
    'Atpara',
    'Barhatta',
    'Durgapur',
    'Kalmakanda',
    'Kendua',
    'Khaliajuri',
    'Madan',
    'Mohanganj',
    'Netrokona Sadar',
    'Purbadhala',
  ],
  'Nilphamari': [
    'Dimla',
    'Domar',
    'Jaldhaka',
    'Kishoreganj',
    'Nilphamari Sadar',
    'Saidpur',
  ],
  'Noakhali': [
    'Begumganj',
    'Chatkhil',
    'Companiganj',
    'Hatiya',
    'Kabirhat',
    'Noakhali Sadar',
    'Senbagh',
    'Sonaimuri',
    'Subarnachar',
  ],
  'Pabna': [
    'Atgharia',
    'Bera',
    'Bhangura',
    'Chatmohar',
    'Faridpur',
    'Ishwardi',
    'Pabna Sadar',
    'Santhia',
    'Sujanagar',
  ],
  'Panchagarh': [
    'Atwari',
    'Boda',
    'Debiganj',
    'Panchagarh Sadar',
    'Tetulia',
  ],
  'Patuakhali': [
    'Bauphal',
    'Dashmina',
    'Dumki',
    'Galachipa',
    'Kalapara',
    'Mirzaganj',
    'Patuakhali Sadar',
    'Rangabali',
  ],
  'Pirojpur': [
    'Bhandaria',
    'Kawkhali',
    'Mathbaria',
    'Nazirpur',
    'Nesarabad',
    'Pirojpur Sadar',
    'Zianagar',
  ],
  'Rajbari': [
    'Baliakandi',
    'Goalandaghat',
    'Kalukhali',
    'Pangsha',
    'Rajbari Sadar',
  ],
  'Rajshahi': [
    'Bagha',
    'Bagmara',
    'Charghat',
    'Durgapur',
    'Godagari',
    'Mohanpur',
    'Paba',
    'Puthia',
    'Tanore',
  ],
  'Rangamati': [
    'Baghaichhari',
    'Barkal',
    'Belaichhari',
    'Juraichhari',
    'Kaptai',
    'Kawkhali',
    'Langadu',
    'Naniarchar',
    'Rajasthali',
    'Rangamati Sadar',
  ],
  'Rangpur': [
    'Badarganj',
    'Gangachara',
    'Kaunia',
    'Mithapukur',
    'Pirgachha',
    'Pirganj',
    'Rangpur Sadar',
    'Taraganj',
  ],
  'Satkhira': [
    'Assasuni',
    'Debhata',
    'Kalaroa',
    'Kaliganj',
    'Satkhira Sadar',
    'Shyamnagar',
    'Tala',
  ],
  'Shariatpur': [
    'Bhedarganj',
    'Damudya',
    'Gosairhat',
    'Naria',
    'Shariatpur Sadar',
    'Zajira',
  ],
  'Sherpur': [
    'Jhenaigati',
    'Nakla',
    'Nalitabari',
    'Sherpur Sadar',
    'Sreebardi',
  ],
  'Sirajganj': [
    'Belkuchi',
    'Chauhali',
    'Kamarkhanda',
    'Kazipur',
    'Raiganj',
    'Shahjadpur',
    'Sirajganj Sadar',
    'Tarash',
    'Ullapara',
  ],
  'Sunamganj': [
    'Bishwamvarpur',
    'Chhatak',
    'Derai',
    'Dharampasha',
    'Dowarabazar',
    'Jagannathpur',
    'Jamalganj',
    'Sullah',
    'Sunamganj Sadar',
    'Shantiganj',
    'Tahirpur',
  ],
  'Sylhet': [
    'Balaganj',
    'Beanibazar',
    'Bishwanath',
    'Companiganj',
    'Fenchuganj',
    'Golapganj',
    'Gowainghat',
    'Jaintiapur',
    'Kanaighat',
    'Osmani Nagar',
    'Sylhet Sadar',
    'Zakiganj',
  ],
  'Tangail': [
    'Basail',
    'Bhuapur',
    'Delduar',
    'Dhanbari',
    'Ghatail',
    'Gopalpur',
    'Kalihati',
    'Madhupur',
    'Mirzapur',
    'Nagarpur',
    'Sakhipur',
    'Tangail Sadar',
  ],
  'Thakurgaon': [
    'Baliadangi',
    'Haripur',
    'Pirganj',
    'Ranisankail',
    'Thakurgaon Sadar',
  ],
};
